# Site settings
title: Biera Solutions
email: dani@danilat.com
description: > 
  Hacemos aplicaciones web y móviles con cariño. 
url: "http://bierasolutions.com" # the base hostname & protocol for your site
twitter_username: bierasolutions

# Build settings
markdown: kramdown
